### ISSUE TITLE
web site coderdbc.com stop working

### ISSUE THREAD

**Issue by cickok** [astand/c-coderdbc#15]
Hello,

firstly i would like to thank you for your great job!

Secondly i have a quiestion. The website https://coderdbc.com/ stop working just in time i start using your app. Are you going to repair it? 

Thank you,
best regards,
Jiri

**Comment by astand** [comment]
Hi, thank you!

Yeah, it seems that the server had been stuck. I fixed it.
I don't update coderdbc website with the newest c-coderdbc release, so I would suggest you to use offline (cli) version, it is always up to date
