### ISSUE TITLE
Incorrect read long string

### ISSUE THREAD

**Issue by DPOH357** [astand/c-coderdbc#16]
[j1939.zip](https://github.com/astand/c-coderdbc/files/9643838/j1939.zip)

When I try to decode j1939.dbc file (attached), the decoder hang.
While debugging, I found a problem with reading the input file. If readstream.getline(line, MAX_LINE) reading a string longer than MAX_LINE, the failure bit will be set in the readstream. To continue reading, you must clear current status (readstream.clear()) and reread remaining data. You code may look like:

    if(readstrm.fail())
    {
      readstrm.clear();
      readstrm.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
    }

**Comment by astand** [comment]
Hi, thanks for noticing.
Fixed in v2.6
