### ISSUE TITLE
coderdbc incorrectly translating scale factor of "1E-007"

### ISSUE THREAD

**Issue by bonjiman** [astand/c-coderdbc#20]
To whom it may concern,

I am a graduate student working on a collegiate design series.  The competition rules require us to publish our outputs over a scoring CAN bus, and they have provided us a DBC file to abide by when transmitting our outputs.

One of the messages is comprised of the following 2 signals:
 `SG_ VehicleLatitude : 7|32@0- (1E-007,0) [-90|90] "deg"  DAQ`
 `SG_ VehicleLongitude : 39|32@0- (1E-007,0) [-180|180] "deg"  DAQ`

As you know, these lines of the DBC state that the conversion factor between the physical and integer values is 10^(-7).  However, the codegen software misinterprets this line by substituting it for a zero.

The output of the codegen is:
`// signal: @VehicleLatitude_ro`
`#define SCORING_VehicleLatitude_ro_CovFactor (0)`

This issue persisted even when the scale factor in the DBC was replaced with a more typical decimal point representation:
 `SG_ VehicleLatitude : 7|32@0- (0.0000001,0) [-90|90] "deg"  DAQ`

As I was writing this issue, we actually found (what we believe to be) one source of the error.  In `c-sigprinter.cpp`, there are several formatted prints that use `%f` rather than something longer like `%.10f` and the number is truncated.  This affects the `CoV`, `toS`, and `fromS` macros.  

====

Another issue is that using scientific notation in the scale factor appears to cause issues in the output.  Using scientific notation caused the codegen to misinterpret physical float values as integer values.

From the output of the codegen:
`#ifdef E_USE_SIGFLOAT`
`  uint64_t VehicleLatitude_phys;`
`#endif // E_USE_SIGFLOAT`

The output should have used the `sigfloat_t` type instead.  This issue can be somewhat fixed by not using scientific notation in DBC definitions, but we have found several other DBC files online where scientific notations are common.

**Comment by astand** [comment]
Hi @bonjiman

Yeah those moments were not implemented fully mathematically correct, probably because I neglected very low scale factors. But it seems now it is time to make more well defined  

Thanks a lot for your participation!

**Comment by moonglow** [comment]
@bonjiman 
as example you can change floating point output format from `%f` to `%.10f`. By default `%f` provides only 6 digits after dot...

**Comment by astand** [comment]
Fixed in v2.7. README for more details
