### ISSUE TITLE
compile error v3.0 

### ISSUE THREAD

**Issue by simoneScaravati** [astand/c-coderdbc#27]
Hi there! 
I'm just trying to compile the project the first time on Windows 10 (compiler SDK VS 2022 x64) 
And I'm getting the error in dbcscanner.cpp(348,30): error C2131
it looks like strlen doesn't work for some reason. 

I tried to simply change the function and using sizeof instead and it compiles (TBT pending) 

_static const size_t VER_MIN_LENGTH = sizeof(versionAttr);//strlen(versionAttr);_

does it make sense? 

ty

**Comment by astand** [comment]
Hi @simoneScaravati 
The original code is not very good, strlen is not constexpr
Will fix it in more clear way
Thanks for report
