### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by sirtapps** [astand/c-coderdbc#3]
Hi, i use the wsl-shell in Windows to compile your project.

I install the build-essentials, so i may missed some depencies. Do you have any clue, what's missing?

`> sudo cmake --build build --config release --clean-first

[  9%] Building CXX object CMakeFiles/coderdbc.dir/codegen/c-main-generator.cpp.o

[ 18%] Building CXX object CMakeFiles/coderdbc.dir/codegen/c-util-generator.cpp.o

[ 27%] Building CXX object CMakeFiles/coderdbc.dir/codegen/conditional-tree.cpp.o

[ 36%] Building CXX object CMakeFiles/coderdbc.dir/codegen/c-sigprinter.cpp.o

[ 45%] Building CXX object CMakeFiles/coderdbc.dir/codegen/filewriter.cpp.o

[ 54%] Building CXX object CMakeFiles/coderdbc.dir/codegen/fs-creator.cpp.o

[ 63%] Building CXX object CMakeFiles/coderdbc.dir/helpers/formatter.cpp.o

[ 72%] Building CXX object CMakeFiles/coderdbc.dir/parser/dbclineparser.cpp.o

[ 81%] Building CXX object CMakeFiles/coderdbc.dir/parser/dbcscanner.cpp.o

[ 90%] Building CXX object CMakeFiles/coderdbc.dir/maincli.cpp.o

[100%] Linking CXX executable coderdbc

/usr/bin/ld: CMakeFiles/coderdbc.dir/codegen/fs-creator.cpp.o: in function 
`FsCreator::PrepareDirectory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
fs-creator.cpp:(.text+0xe3): undefined reference to `std::filesystem::create_directory(std::filesystem::__cxx11::path const&)'

/usr/bin/ld: fs-creator.cpp:(.text+0x20c): undefined reference to `std::filesystem::create_directory(std::filesystem::__cxx11::path const&)'

/usr/bin/ld: fs-creator.cpp:(.text+0x263): undefined reference to `std::filesystem::create_directory(std::filesystem::__cxx11::path const&)'

/usr/bin/ld: CMakeFiles/coderdbc.dir/codegen/fs-creator.cpp.o: in function `std::filesystem::__cxx11::path::path<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::filesystem::__cxx11::path>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::filesystem::__cxx11::path::format)':
fs-creator.cpp:(.text._ZNSt10filesystem7__cxx114pathC2INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES1_EERKT_NS1_6formatE[_ZNSt10filesystem7__cxx114pathC5INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES1_EERKT_NS1_6formatE]+0x64): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'

/usr/bin/ld: CMakeFiles/coderdbc.dir/maincli.cpp.o: in function `std::filesystem::exists(std::filesystem::__cxx11::path const&)':
maincli.cpp:(.text._ZNSt10filesystem6existsERKNS_7__cxx114pathE[_ZNSt10filesystem6existsERKNS_7__cxx114pathE]+0x14): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'

collect2: error: ld returned 1 exit status

make[2]: *** [CMakeFiles/coderdbc.dir/build.make:219: coderdbc] Error 1

make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/coderdbc.dir/all] Error 2

make: *** [Makefile:84: all] Error 2
`

**Comment by astand** [comment]
https://en.cppreference.com/w/cpp/filesystem

I bet that the problem with std::filestream, you need to build the app with enabled c++17.
It seems that you need to either to sovle CMakeList.txt configuration or install c++17 libraries.

**Comment by astand** [comment]
Sorry but I am not a pro of 'cmake')
