### ISSUE TITLE
***-config.h reference still present even when using -noconfig

### ISSUE THREAD

**Issue by Ayman-Elzubair** [astand/c-coderdbc#30]
Hi @astand

when generating with options    
-noconfig:    no {drivername}-config and dbccodeconfig generation
-nofmon:      no ***-fmon.c generation

I still see in the generated lib header a reference to -config.h  and also inside -fmon.h
is it intended behavior?

**Comment by astand** [comment]
Hi @Ayman-Elzubair 

Yes, this is intended behavior. -config file may have user's application configuration, if you generate the sources right into the project you would probably desire to not overwrite your configuration
fmon - frame monitoring is part of the main lib. You will always see includes of that module. -nofmon is used in the same scenario - when you implemented your own monitoring strategy and do not want to overwrite it
