### ISSUE TITLE
Is function for TX direction available in util file?

### ISSUE THREAD

**Issue by shevu** [astand/c-coderdbc#4]
Hello.
In my DBC file I have declared TX message. I don't know why but it's appear in xxx_Receive function.

Is it a BUG or intended action?

**Comment by astand** [comment]
Hi, I am not sure that understood the problem. 
There is no declaration on the DBC file level which can determine choice of *_tx_t or *_rx_t struct.
To divide frames on Tx/Rx structs in source code you need to put Message IDs to dedicated containers of **groups** variable, look at the line 84 of maincli.cpp.
As you can see by default ALL frames from DBC are going to RX group.

**Comment by icolwell-as** [comment]
Hi @astand, I am running into the same issue. Thanks for pointing out the line in maincli.cpp, that can work temporarily.

All dbc files that I have used have a "network nodes" defined and specified with each message definition. It usually appears like this:

```
BU_: CUSTOMER_ECU SOME_ECU

BO_ 341 BMS_1: 8 SOME_ECU
```
In the above case, the `BU_` line is specifying what network nodes exist in the rest of the file.
The `BO_` message line specifies that the node called "SOME_ECU" is one of the nodes that will transmit this `BMS_1` message.

I think the best solution is to add a new feature that allows the user to specify which network node the generated code is targeting. For example, if you run the tool and specify "SOME_ECU" the generated code will have a receive function for all messages that the "SOME_ECU" node can receive, and transmit function for all messages that the "SOME_ECU" node can transmit.

Does that make sense?

**Comment by astand** [comment]
Hi @icolwell-as.
Yes, it makes sense. But my usual using case is not relying on subscriptions inside dbc file, I have a json configuration files which are describes specific nodes and CanFrames collection for TX/RX for this specific node. 
I plan to add passing such json to CLI c-coderdbc.

I will think about idea about "network nodes" too.

**Comment by astand** [comment]
All network nodes from DBC file can be parsed and specific binutil for each node is generated. (v1.6)

**Comment by icolwell-as** [comment]
Thanks @astand for implementing this so quickly! Much appreciated.
