### ISSUE TITLE
License of generated code

### ISSUE THREAD

**Issue by icolwell-as** [astand/c-coderdbc#5]
Hi There!

First off, thanks for creating this auto-generator, it works great!
I noticed the licence of this repository and the `coderdbc` command-line tool is GPL-3.0.

However, I assume all code generated by the tool is free of any type of license or conditions of any kind?
Just wanted to double-check.

Thanks!

**Comment by astand** [comment]
Hello, thanks for feedback!

All the files that are generated by c-coderdbc program have a WTFPL License.
