### ISSUE TITLE
incorrect parsing of signed 8 bit signals

### ISSUE THREAD

**Issue by 2Black2** [astand/c-coderdbc#8]
![Image](https://user-images.githubusercontent.com/99673537/153904918-a0e1b43c-34b6-410d-99b6-563ce1947b25.png)
thank you for inventing and sharing this tool!
I believe I have found a bug related on **unpack** of signals defined as **signed** 8 bit 
code generated is the following:
__m->YYY_signal1_ro = (_d[3] & (0xFFU));_
but YYY_signal1_ro (int16_t) will contain 0x00DF instead of 0x805F
so when the following will be executed
_#ifdef CANDB_MONDIAL_USE_SIGFLOAT //this is defined
  _m->YYY_signal1_phys = CANDB_MONDIAL_YYY_signal1_ro_fromS(_m->YYY_signal1_ro);
#endif // CANDB_MONDIAL_USE_SIGFLOAT_
generate
00DF * factor + offset 
instead of
0x805F * factor + offset 

for a fast solution I modified the first line in 
__m->YYY_signal1_ro = (int16_t)( (int8_t)(_d[3] & (0xFFU)));_
but many other solution could be implemented.

Fell free to contact me for any additional information

**Comment by astand** [comment]
Hi, thanks for pointing this issue.
Actually there a few related to each other problems with **Signed** signals. I will try to fix all the problems soon.

**Comment by 2Black2** [comment]
Thanks to you for your support!

**Comment by astand** [comment]
Hi
I hope the v2.1 solves the problem. I made some tests but actually don't have enough DBCs with signed signals.
